### ISSUE TITLE
Option to use uncss without specifying in- or output css filename

### ISSUE THREAD

**Issue by ismay** [uncss/grunt-uncss#109]
It would be useful if uncss could accept just the html it should parse, without having to specify an in- or output css filename. Otherwise this task is difficult to use with filerevving.

With something like the following example config:

``` javascript
uncss: {
  dist: {
    cwd: 'dist',
    src: ['**/*.html'],
  }
}
```

It could parse the html for the location of the css to process and just overwrite all found css (when parsing the html it should account for a potential base tag, maybe the options could allow for a `base` boolean so that the parser knows whether the css' location is relative or absolute).

That way revved css isn't a problem, and uncss would be more dynamic (like autoprefixer for example). Also, you wouldn't have to include it in the middle of the usemin queue, before the css is revved (if you're using it with usemin).

**Comment by XhmikosR** [comment]
This should be done upstream.
