### ISSUE TITLE
GitHub Actions CI

### ISSUE THREAD

**Issue by XhmikosR** [uncss/grunt-uncss#221]
@giakki can you register for GitHub Actions? https://github.com/features/actions

**Comment by giakki** [comment]
Done! Not sure if I should give you some permissions, ping me if I do!

**Comment by XhmikosR** [comment]
Nope, all good https://github.com/uncss/grunt-uncss/actions :)

**Comment by XhmikosR** [comment]
You can remove the Travis CI App from grunt-uncss completely now.
